# Generated by Django 3.1.1 on 2020-10-10 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chaps', '0002_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='chap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='chaps.chap'),
        ),
        migrations.AlterField(
            model_name='pair',
            name='color',
            field=models.CharField(blank=True, default='color:black;', max_length=20),
        ),
        migrations.AlterField(
            model_name='pair',
            name='status',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
