# Generated by Django 3.1.1 on 2020-10-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaps', '0003_auto_20201010_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='chap',
            name='sum1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chap',
            name='sum2',
            field=models.IntegerField(default=0),
        ),
    ]
