# Generated by Django 3.1.1 on 2020-10-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaps', '0004_auto_20201015_1222'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('textAnswered', models.CharField(max_length=200)),
                ('pairAskedID', models.IntegerField(default=0)),
                ('callType', models.IntegerField(default=0)),
                ('lr', models.CharField(default='L', max_length=2)),
            ],
        ),
    ]
