# Generated by Django 3.1.1 on 2020-10-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaps', '0005_call'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='lr',
        ),
        migrations.AddField(
            model_name='chap',
            name='lr',
            field=models.CharField(default='L', max_length=2),
        ),
        migrations.AlterField(
            model_name='pair',
            name='color',
            field=models.CharField(blank=True, default='color:black', max_length=20),
        ),
    ]
