# Generated by Django 3.1.1 on 2020-10-21 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaps', '0006_auto_20201020_1952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='callType',
        ),
        migrations.AddField(
            model_name='chap',
            name='ct',
            field=models.IntegerField(default=0),
        ),
    ]
