# Generated by Django 3.1.1 on 2020-10-21 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaps', '0007_auto_20201021_0858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chap',
            name='ct',
        ),
        migrations.AddField(
            model_name='call',
            name='callType',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chap',
            name='rs',
            field=models.CharField(default='r', max_length=2),
        ),
    ]
