# Generated by Django 3.1.1 on 2020-10-24 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaps', '0008_auto_20201021_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='chap',
            name='lastCalledNum',
            field=models.IntegerField(default=0),
        ),
    ]
