# Generated by Django 3.1.1 on 2020-10-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chaps', '0009_chap_lastcallednum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chap',
            name='lastCalledNum',
        ),
        migrations.AddField(
            model_name='chap',
            name='toCallNum0',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chap',
            name='toCallNum1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chap',
            name='toCallNum2',
            field=models.IntegerField(default=0),
        ),
    ]
